
class BerettaM9 : MercilessWeapon replaces Pistol
{
    Default{
		+Weapon.NOAUTOFIRE
        +Weapon.WIMPY_WEAPON
        Weapon.SelectionOrder 1900;
        Weapon.AmmoUse 1;
        Weapon.AmmoGive 20;
        Weapon.AmmoType "Clip";
        Obituary "$OB_MPPISTOL";
        Inventory.PickupMessage "$PICKUP_PISTOL_DROPPED";
        Tag "$TAG_PISTOL";

        Weapon.WeaponScaleY 0.9;
		Weapon.WeaponScaleX 0.9;
        MercilessWeapon.VerticalRecoil 0.8;
        MercilessWeapon.HorizontalRecoil 0;
    }


    States
    {
    Ready:
        M9PS A 1 A_WeaponReady();
        loop;
    Deselect:
        M9PS A 1 A_Lower(10);
        loop;
    Select:
        M9PS A 1 A_Raise(10);
        loop;
	Fire:
        // TODO:
        //  randomnly offset weapon left-right -- Ongoing? want to make it more predictable
        //  spawn bullet casings
        TNT1 A 0 {
            MD_FireWeapon(2, 0, -1, 7 * random(1,3));
            A_WeaponOffset(random2[wpnoffs](3), 0, WOF_ADD|WOF_KEEPY);
            MD_SpawnBarrelSmoke(minsize:0.1, maxsize:0.25, sizestep:1.5);
            // MD_ShakeCamera((0, 0.4, 0.5), 4);
            A_QuakeEx(0.0, 0.0, 1.0, 5, 0, tremrad:50, sfx:"", flags:QF_RELATIVE|QF_WAVE, mulwavez:0.8, rollintensity:frandom[shk](0.0, 0.8), rollwave:1.0);
            A_ZoomFactor(0.99);

            MD_MuzzleFlash(STYLE_Normal);
            A_StartSound("weapons/m9/fire", CHAN_WEAPON, CHANF_OVERLAP, pitch:frandom(0.97, 1.03)); // placeholder sound...
        } 
		M9PF AB 1;
		// M9PF AB 1 A_WeaponOffset(0, 2.0, WOF_ADD|WOF_KEEPX);
        M9PF C 1 A_ZoomFactor(1.0);
		// M9PF C 1;
        M9PF D 2 {
            A_WeaponReady();
            A_WeaponOffset(0, WEAPONTOP, WOF_INTERPOLATE);
        }
        M9PF E 2 A_WeaponReady();
		Goto Ready;
	MuzzleFlash:
        // TODO:
        //  multiple muzzleflash variants (randomnly chosen)
        TNT1 A 0 {
            A_AttachLight('muzzlelight', DynamicLight.PointLight, color(255, 248, 220), 
                radius1: random(130,200), 
                radius2: 0,
                flags: DynamicLight.LF_ATTENUATE,
                ofs: (0,0,self.player.viewz)
                );
        }
        M9FF AA 1 bright;
        TNT1 A 0 A_Jump(64, 2);
        M9FF B 1 bright {
            A_OverlayRenderstyle(OverlayID(), STYLE_Add);
            A_OverlayOffset(OverlayID(), crandom2(3), 0);
            A_OverlayPivot(OverlayID(), 0.5, 0.5);
            A_OverlayScale(OverlayID(), frandom(0.75, 1.0), 0);
            A_OverlayRotate(OverlayID(), crandom2(8));
        }
        TNT1 A 0 A_RemoveLight('muzzlelight');
		stop;
    Spawn:
        PIST A -1;
        Stop;
    }
}