
class BerettaM9 : MercilessWeapon replaces Pistol
{
    Default{
		+Weapon.NOAUTOFIRE
        +Weapon.WIMPY_WEAPON
        Weapon.SelectionOrder 1900;
        Weapon.AmmoUse 1;
        Weapon.AmmoGive 20;
        Weapon.AmmoType "Clip";
        Obituary "$OB_MPPISTOL";
        Inventory.PickupMessage "$PICKUP_PISTOL_DROPPED";
        Tag "$TAG_PISTOL";

        Weapon.WeaponScaleY 0.9;
		Weapon.WeaponScaleX 0.9;
        MercilessWeapon.VerticalRecoil 0.5;
        MercilessWeapon.HorizontalRecoil 0;
    }


    States
    {
    Ready:
        M9PS A 1 A_WeaponReady();
        loop;
    Deselect:
        M9PS A 1 A_Lower(10);
        loop;
    Select:
        M9PS A 1 A_Raise(10);
        loop;
	Fire:
        // TODO:
        //  randomnly offset weapon left-right -- Ongoing? want to make it more predictable
        //  spawn bullet casings
        TNT1 A 0 {
            MD_FireWeapon(2, 0, -1, 7 * random(1,3));
            A_WeaponOffset(frandom[wpnoffs](-1.0, 1.0), 0, WOF_ADD|WOF_KEEPY);
            MD_SpawnBarrelSmoke(howMany:random(1,2), minsize:0.08, maxsize:0.15, sizeStep:3, startAlpha:0.9);
            // MD_TestBarrelSmoke();
            MD_ShakeCamera((0, 0.2, 0.4), 5, frandom[shk](0.0, 1.2));
            A_ZoomFactor(0.98);

            MD_MuzzleFlash();
            A_StartSound("weapons/m9/fire", CHAN_WEAPON, CHANF_OVERLAP, pitch:frandom(0.97, 1.03)); // placeholder sound...
        } 
		M9PF AB 1;
		// M9PF AB 1 A_WeaponOffset(0, 2.0, WOF_ADD|WOF_KEEPX);
        M9PF C 1 {
            A_ZoomFactor(1.0);
            MD_SpawnCasings("GenericCasing", -11.5, -15.5, 37.5, frandom(-1,3), frandom(2,5), frandom(1.5,3.5));
        }
        M9PF DEEFF 1 A_WeaponReady();
		Goto Ready;
	MuzzleFlash:
        // TODO:
        //  multiple muzzleflash variants (randomnly chosen)
        TNT1 A 0 {
            A_AttachLight('muzzlelight', DynamicLight.PointLight, color(255, 205, 205), 
                radius1: random(80,120), 
                radius2: 0,
                flags: DynamicLight.LF_ATTENUATE,
                ofs: (0,0,self.player.viewz)
                );
        }
        TNT1 A 0 A_Jump(256, "MuzzleFlash_Alt1", "MuzzleFlash_Alt2", "MuzzleFlash_Alt3");
        // TNT1 A 0 A_Jump(64, 2);
        // M9FF B 1 bright {
        //     A_OverlayRenderstyle(OverlayID(), STYLE_Add);
        //     A_OverlayOffset(OverlayID(), crandom2(3), 0);
        //     A_OverlayPivot(OverlayID(), 0.5, 0.5);
        //     A_OverlayScale(OverlayID(), frandom(0.75, 1.0), 0);
        //     A_OverlayRotate(OverlayID(), crandom2(8));
        // }
		// stop;
    MuzzleFlash_Alt1:
        M9FF AA 1 bright;
        goto FinishFlash;
    MuzzleFlash_Alt2:
        M9FF CB 1 bright;
        goto FinishFlash;
    MuzzleFlash_Alt3:
        M9FF DD 1 bright;
        goto FinishFlash;
    FinishFlash:
        TNT1 A 0 A_RemoveLight('muzzlelight');
        stop;
    Spawn:
        PIST A -1;
        Stop;
    }
}