
class MercilessSSG : MercilessWeapon replaces SuperShotgun
{
    Default{
		+Weapon.NOAUTOFIRE
		Weapon.SelectionOrder 400;
		Weapon.AmmoUse 2;
		Weapon.AmmoGive 8;
		Weapon.AmmoType "Shell";

		Inventory.PickupMessage "$GOTSHOTGUN2";
		Obituary "$OB_MPSSHOTGUN";
		Tag "$TAG_SUPERSHOTGUN";

		Weapon.WeaponScaleY 0.9;
		Weapon.WeaponScaleX 0.9;
        MercilessWeapon.VerticalRecoil 5.0;
        MercilessWeapon.HorizontalRecoil 0;
    }

    States
    {
	Ready:
		YSSG A 1 A_WeaponReady();
		Loop;
	Deselect:
		YSSG A 1 A_Lower(10);
		Loop;
	Select:
		YSSG A 1 A_Raise(10);
		Loop;
	Fire:
		TNT1 A 0 {
			MD_FireWeapon(11.2, 7.1, 20, 6);
			MD_SpawnBarrelSmoke(3, startAlpha:0.5, minSize:0.3, maxSize:0.4, sizeStep:2.5);
			// MD_ShakeCamera((1.2, 0.0, 2.2), 7, 1.3, 1.0);
            // A_QuakeEx(0.0, 1.5, 2.0, 7, 0, tremrad:50, sfx:"", flags:QF_RELATIVE|QF_WAVE, mulwavez:2.0, rollintensity:frandom[shk](0.5, 1.0), rollwave:2.0);
			A_ZoomFactor(0.93);
			A_WeaponOffset(random2[wpnoffs](3), 0, WOF_ADD|WOF_KEEPY);
			A_StartSound("weapons/ssg/fire", CHAN_WEAPON, CHANF_OVERLAP, pitch:frandom(0.95, 1.05));
		}
		YSSF A 1;
		YSSF B 1 { 
			A_QuakeEx(0.0, 1.8, 2.5, 7, 0, tremrad:50, sfx:"", flags:QF_RELATIVE|QF_WAVE, mulwavez:2.0, rollintensity:frandom[shk](0.8, 1.5), rollwave:2.0);
			MD_MuzzleFlash(STYLE_Normal);
		}
		YSSF CDD 1 A_ZoomFactor(1.0);
		YSSF EF 1 A_WeaponOffset(0, WEAPONTOP, WOF_INTERPOLATE);
		TNT1 A 0 A_CheckReload();
		// Reloading
		// YSSR BC 2;
		YSSR BBCDEFGH 1;
		YSSR IJK 2;
		// YSSR JK 1;
		YSSR L 1 A_StartSound("weapons/ssg/reloadopen", CHAN_WEAPON, CHANF_OVERLAP);
		YSSR MN 2;
		// YSSR N 1;
		YSSR OPQRS 1;
		YSSR T 1;
		YSSR V 1 A_StartSound("weapons/ssg/reloadshell", CHAN_WEAPON, CHANF_OVERLAP);
		YSSR VW 1;
		YSSR XYZ 2;
		ZSSR AB 1;
		ZSSR C 1 A_StartSound("weapons/ssg/reloadclose", CHAN_WEAPON, CHANF_OVERLAP); 
		// ZSSR D 2;
		ZSSR DDEEF 1;
		ZSSR GHI 1 A_WeaponReady();
		Goto Ready;
	MuzzleFlash:
		TNT1 A 0 {
            A_AttachLight('muzzlelight', DynamicLight.PointLight, color(255, 150, 150), 
                radius1: random(190,250), 
                radius2: 0,
                flags: DynamicLight.LF_ATTENUATE,
                ofs: (0,0,self.player.viewz)
                );
			A_OverlayAlpha(OverlayID(), 0.9);
        }
		YSSM AB 1 bright {
            A_OverlayPivot(OverlayID(), 0.5, 0.5);
            A_OverlayScale(OverlayID(), frandom(1.0, 1.1), 0);
			A_OverlayRotate(OverlayID(), crandom2(4));
		}
		TNT1 A 1;
        TNT1 A 0 A_RemoveLight('muzzlelight');
		stop;
	Spawn:
		SGN2 A -1;
		Stop;
    }
}

