
class MercilessWeapon : Weapon
{
    // Constants
    const FLASH_LAYER = -100;
    /* Weapon Sway */
    const SWAY_SENSITIVITY_Y = 12.0;
    const SWAY_MIN_Y = 27.0;
	const SWAY_MAX_Y = 42.0;

    static const String smokeSprites[] = {
        "WPNSMOKEVAR1_1",
        "WPNSMOKEVAR2_1",
        "WPNSMOKEVAR3_1",
        "WPNSMOKEVAR4_1",
        "WPNSMOKEVAR5_1",
        "WPNSMOKEVAR6_1",
        "WPNSMOKEVAR7_1",
        // mirrored versions
        "MIRROR_WPNSMOKEVAR1_1",
        "MIRROR_WPNSMOKEVAR2_1",
        "MIRROR_WPNSMOKEVAR3_1",
        "MIRROR_WPNSMOKEVAR4_1",
        "MIRROR_WPNSMOKEVAR5_1",
        "MIRROR_WPNSMOKEVAR6_1",
        "MIRROR_WPNSMOKEVAR7_1"
    };

    // Variables
    PlayerPawn playerOwner;
    double verticalRecoil;
    double horizontalRecoil;
    double recoilCrouchFactor;

    // Properties
    property VerticalRecoil : verticalRecoil;
    property HorizontalRecoil : horizontalRecoil;
    property RecoilCrouchFactor : recoilCrouchFactor;

    Default{
        Weapon.KickBack 100;

        Weapon.BobRangeY 0.75;
        Weapon.BobRangeX 0.8;
        Weapon.BobStyle "Inverse";
        Weapon.BobSpeed 1.3;

        MercilessWeapon.VerticalRecoil 0;
        MercilessWeapon.HorizontalRecoil 0;
        MercilessWeapon.RecoilCrouchFactor 1;
    }


    /****************************************
           VIRTUAL FUNCTION OVERRIDES
    ****************************************/
    
    override void DoEffect()
    {
        Super.DoEffect();
        // Weapon Sway code below was taken from Diamond Dragon
        //  and was first made by Nash Muhandes, adapted & edited for my use.
        if( owner && owner is "PlayerPawn" )
        {
            //  TODO
            //      Make this sway configurable and also
            //      add horizontal sway obviously.
            if( !playerOwner ) {
                playerOwner = PlayerPawn(owner);
            }

            let psp = playerOwner.player.psprites;
            let wep = playerOwner.player.ReadyWeapon;
            if( !psp || !wep ) return;

            // vertical offset
            double ypitch = -playerOwner.pitch;
            ypitch = SWAY_SENSITIVITY_Y * ypitch / 90.0;

            bool bCanSway = (
                        (playerOwner.player.WeaponState & WF_WEAPONREADY)
                        || (playerOwner.player.WeaponState & WF_WEAPONREADYALT)
                        || (playerOwner.player.WeaponState & WF_WEAPONRELOADOK)
                        || (playerOwner.player.WeaponState & WF_WEAPONZOOMOK)
                        || (playerOwner.player.WeaponState & WF_WEAPONSWITCHOK)
                    );

            // main offset logic
            if( psp && bCanSway )
            {
                psp.y = ypitch + 32;

                // add jump velocity to Y
                // psp.y += (plr.Vel.Z * 2);
                psp.y = clamp(psp.y, SWAY_MIN_Y, SWAY_MAX_Y);
            }
        }
    }



    /***************************************
          CUSTOM (ACTION) FUNCTIONS
    ***************************************/

    // Shooting wrapper
    action 
    void MD_FireWeapon(
        double horzSpread, double vertSpread, int numBullets, int damagePerBullet, int flags = FBF_USEAMMO|FBF_NOFLASH|FBF_NORANDOM)
    {
        if( invoker.verticalRecoil != 0 ) {
            A_SetPitch(self.pitch - GetRealRecoil(abs(invoker.verticalRecoil)), SPF_FORCECLAMP);
        }
        if( invoker.horizontalRecoil != 0 ) {
            A_SetAngle(self.angle + GetRealRecoil(invoker.horizontalRecoil));
        }

        //  TODO:
        //      Add different bullet puffs for weapons                     VVVV
        A_FireBullets(horzSpread, vertSpread, numBullets, damagePerBullet, "BulletPuff", flags);
    }


    // Standard muzzleflash creation for weapons
    action 
    void MD_MuzzleFlash(int renderstyle = STYLE_Add)
    {
        A_Overlay(invoker.FLASH_LAYER,            "MuzzleFlash");
        A_OverlayFlags(invoker.FLASH_LAYER,       PSPF_RENDERSTYLE|PSPF_ALPHA, set:true);
        A_OverlayRenderstyle(invoker.FLASH_LAYER, renderstyle);
        A_OverlayAlpha(invoker.FLASH_LAYER,       0.5);
    }


    // Better wrapper for a_quakeex
    action 
    void MD_ShakeCamera(Vector3 xyz, double duration, double rollintensity = 0.5, double rollwave = 1.0, int flags = QF_RELATIVE|QF_SCALEDOWN)
    {
        A_QuakeEx(xyz.x, xyz.y, xyz.z, duration, 0, tremrad:64, sfx:"", flags:flags, rollintensity:rollintensity, rollwave:rollwave);
    }


    // Spawn bullet casings at the specified offsets and velocity.
    action 
    void MD_SpawnCasings(class<Actor> casing, 
                                double xOfs = 0, 
                                double yOfs = 0, 
                                double zOfs = 0, 

                                double xVel = 0, 
                                double yVel = 0, 
                                double zVel = 0
                                )
    {
		// Vector3 ofs = pmo.pos + (0, 0, plr.viewheight - GetFloorTerrain().footclip);       <-- Beautiful Doom
        if( !self.player ) {
            return;
        }

        Vector3 spos, svel;
        spos = GetGlobalPlayerOffs((xOfs, yOfs, zOfs));
        svel = GetGlobalPlayerOffs((xVel, yVel, zVel), isVelocity:true);
        /* The setup for RelativeToGlobalCoords is pretty much the same as SpawnBarrelSmoke.
                I've written a function to do those 2 things at once. 
                Maybe it's just overcomplicating things but for me it becomes easier to understand... 
        */

        let cas = Spawn(casing, spos);
        if( cas )
        {
			cas.vel = svel;
			cas.angle = self.angle;
			cas.target = self;	//so the casings dont collide with the shooter

            invoker.SpawnCasingSmoke(spos, svel*0.1);
        }
    }


    // Spawns smoke particles at the gun's barrel.
	action 
    void MD_SpawnBarrelSmoke(int howMany = -1,
                                int style = STYLE_Add, 
                                double minSize = 0.2, 
                                double maxSize = 0.4, 
                                double sizeStep = 2,
                                double startAlpha = 0.6
                                )
	{

        Vector3 posofs, velofs, spos, svel;
        double rndroll;
        String smokename;
		double fovOfs = (120 - self.player.desiredfov) / 3.f;
        
        if( howMany <= 0 ) {
            howMany = random[smk](1, 3);
        }
        
        for( int i = 0; i < howMany; i++ )
        {
            FSpawnParticleParams params;
            
            //  Setting up variables
            posofs = (frandom[smk](14, 15), frandom[smk](-18, -17), frandom[smk](28.0, 33.0));
            velofs = (frandom[smk](-0.5, 0.0), frandom[smk](-0.7, 0.7), frandom[smk](0.7, 0.9));
            
            spos = GetGlobalPlayerOffs(posofs);
            svel = GetGlobalPlayerOffs(velofs, isVelocity:true);
            params.pos = spos;
            params.vel = svel;

            //  Other basic parameters
            params.style = style;
            params.lifetime = 9; // enough for the smokes

            params.flags = SPF_ROLL|SPF_ROLLCENTER|SPF_LOCAL_ANIM;
            params.startroll = 90+frandom[smk](-5, 5);
            params.rollvel = (velofs.y*1.25)*-1;

            params.startalpha = startAlpha;
            params.fadestep = -1;
            params.sizestep = sizeStep;
            
            //  Texturing the particle
            params.color1 = "";
            smokename = invoker.smokeSprites[ random[smk](0, invoker.smokeSprites.Size()-1) ]; 
            params.texture = TexMan.CheckForTexture(smokename);
            int w, h;
            [w, h] = TexMan.GetSize(params.texture);
            params.size = h * (frandom[smk](minSize, maxSize));

            level.SpawnParticle(params);
        }

	}



    /***************************************
          HELPER FUNCTIONS & MISC
    ***************************************/

    protected action // maybe try not making this an action function?
    Vector3 GetGlobalPlayerOffs(Vector3 offsets, bool isVelocity = false)
    {
        if( !self.player) {
            return (0,0,0); // this shouldn't happen
        }

        Vector3 viewAngles = (self.angle, self.pitch, self.roll);
        Vector3 startVec;
        if( isVelocity ) {
            startVec = (self.vel.xy, 0);
        }
        else
        {
            double fovOfs = (120 - self.player.desiredfov) / 3.f;
            offsets.z -= (self.player.viewz - self.pos.z) / self.player.CrouchFactor;
            offsets.y *= invoker.WeaponScaleX;
            offsets = (self.radius + offsets.x - (5.0 * abs(sin(self.pitch))) + fovOfs, self.radius + offsets.y, offsets.z);
            startVec = (self.pos.xy, self.player.viewz);
        }
        
        return MDUtils.RelativeToGlobalCoords(startVec, viewAngles, offsets);
    }


    void SpawnCasingSmoke(Vector3 position, Vector3 velocity)
    {
        static const String casingSmokes[] = {
            "BCSMA0",
            "BCSMB0",
            "BCSMC0",
            "BCSMD0"
        };
        
        FSpawnParticleParams params;
        params.pos = position;
        // initially i was randomizing the whole velocity
        //  but then i realized that i was literally losing the relative offsets which are the backbone of this whole
        //  casing/smoke spawning logic to work properly
        let rndz = frandom[smk](-0.05, 0.10);
        velocity.z = rndz;
        params.vel = velocity;
        params.lifetime = 6;
        params.startalpha = 1.0;
        params.fadestep = -1;
        params.sizestep = frandom[smk](0.5, 1.2);
        
        params.color1 = "";
        let smok = casingSmokes[ random[smk](0, casingSmokes.Size()-1) ]; 
        params.texture = TexMan.CheckForTexture(smok);
        int w, h;
        [w, h] = TexMan.GetSize(params.texture);
        params.size = h * 0.05;
        
        params.flags = SPF_ROLL|SPF_ROLLCENTER;
        params.startroll = 135 + frandom[smk](-5,5);
        params.rollvel = velocity.y * (frandom[smk](5,6) * randompick[smk](-1,1));

        // params.style = STYLE_Add;
        level.SpawnParticle(params);
    }


    action
    double GetRealRecoil(double recoil)
    {
        return (self.player.crouchfactor ~== 0.5) ? recoil*invoker.recoilCrouchFactor : recoil;
    }
}