
class MercilessWeapon : Weapon
{
    // Constants
    const FLASH_LAYER = -100;
    /* Weapon Sway */
    const SWAY_SENSITIVITY_Y = 12.0;
    const SWAY_MIN_Y = 27.0;
	const SWAY_MAX_Y = 42.0;

    // Variables
    PlayerPawn playerOwner;
    double verticalRecoil;
    double horizontalRecoil;
    
    // Properties
    property VerticalRecoil : verticalRecoil;
    property HorizontalRecoil : horizontalRecoil;

    Default
    {
        Weapon.KickBack 100;

        Weapon.BobRangeY 0.75;
        Weapon.BobRangeX 0.8;
        Weapon.BobStyle "Inverse";
        Weapon.BobSpeed 1.3;

        MercilessWeapon.VerticalRecoil 0;
        MercilessWeapon.HorizontalRecoil 0;
    }

    /*
        Virtual function overrides
    */
    override void DoEffect()
    {
        Super.DoEffect();
        // Weapon Sway code below was taken from Diamond Dragon
        //  and was first made by Nash Muhandes, adapted & edited for my use.
        if( owner && owner is "PlayerPawn" )
        {
            //  TODO
            //      Make this sway configurable and also
            //      add horizontal sway obviously.
            if( !playerOwner ) {
                playerOwner = PlayerPawn(owner);
            }

            let psp = playerOwner.player.psprites;
            let wep = playerOwner.player.ReadyWeapon;
            if( !psp || !wep ) return;

            // vertical offset
            double ypitch = -playerOwner.pitch;
            ypitch = SWAY_SENSITIVITY_Y * ypitch / 90.0;

            bool bCanSway = (
                        (playerOwner.player.WeaponState & WF_WEAPONREADY)
                        || (playerOwner.player.WeaponState & WF_WEAPONREADYALT)
                        || (playerOwner.player.WeaponState & WF_WEAPONRELOADOK)
                        || (playerOwner.player.WeaponState & WF_WEAPONZOOMOK)
                        || (playerOwner.player.WeaponState & WF_WEAPONSWITCHOK)
                    );

            // main offset logic
            if( psp && bCanSway )
            {
                psp.y = ypitch + 32;

                // add jump velocity to Y
                // psp.y += (plr.Vel.Z * 2);
                psp.y = clamp(psp.y, SWAY_MIN_Y, SWAY_MAX_Y);
            }
        }
    }

    /*
        Custom functions & action functions
    */
    // Simplified shooting logic + mod extras
    action void A_MFireWeapon(
            double horzSpread, double vertSpread, int numBullets, int damagePerBullet, 
            int flags = FBF_USEAMMO|FBF_NOFLASH|FBF_NORANDOM)
    {
        // Physical recoil applied to player's view
        if( invoker.verticalRecoil != 0 ) {
            A_SetPitch(self.pitch - abs(invoker.verticalRecoil), SPF_INTERPOLATE|SPF_FORCECLAMP);
        }
        if( invoker.horizontalRecoil != 0 ) {
            A_SetAngle(self.angle + invoker.horizontalRecoil, SPF_INTERPOLATE);
        }

        // Shooting
        //  TODO:
        //      Add different bullet puffs for weapons                     VVVV
        A_FireBullets(horzSpread, vertSpread, numBullets, damagePerBullet, "BulletPuff", flags, missile:"MBulletTracer", spawnheight:0, spawnofs_xy:0);
    }
    
    // Standard muzzleflash creation for weapons
    action void A_MCreateFlash(int renderstyle = STYLE_Add)
    {
        A_Overlay(invoker.FLASH_LAYER,            "MuzzleFlash");
        A_OverlayFlags(invoker.FLASH_LAYER,       PSPF_RENDERSTYLE|PSPF_ALPHA, set:true);
        A_OverlayRenderstyle(invoker.FLASH_LAYER, renderstyle);
        A_OverlayAlpha(invoker.FLASH_LAYER,       0.5);
    }

    // better wrapper for a_quakeex
    // TODO: Of course, this may need adjustments over time, and take weapon recoil values into account
    action void A_MShakeCamera(Vector3 xyz, double duration)
    {
        A_QuakeEx(xyz.x, xyz.y, xyz.z, duration, 0, tremrad:50, sfx:"", flags:WOF_RELATIVE, rollintensity:0.5, rollwave:1.0);
    }

}