
class MercilessWeapon : Weapon
{
    // Constants
    const FLASH_LAYER = -100;
    /* Weapon Sway */
    const SWAY_SENSITIVITY_Y = 12.0;
    const SWAY_MIN_Y = 27.0;
	const SWAY_MAX_Y = 42.0;

    static const String smokeSprites[] = {
        "YSMKA0",
        "YSMKB0",
        "YSMKC0",
        "YSMKD0",
        "YSMKE0",
        "YSMKF0",
        "YSMKG0"
    };

    // Variables
    PlayerPawn playerOwner;
    double verticalRecoil;
    double horizontalRecoil;
    
    // Properties
    property VerticalRecoil : verticalRecoil;
    property HorizontalRecoil : horizontalRecoil;

    Default
    {
        Weapon.KickBack 100;

        Weapon.BobRangeY 0.75;
        Weapon.BobRangeX 0.8;
        Weapon.BobStyle "Inverse";
        Weapon.BobSpeed 1.3;

        MercilessWeapon.VerticalRecoil 0;
        MercilessWeapon.HorizontalRecoil 0;
    }


    /*
        Virtual function overrides
    */
    
    override void DoEffect()
    {
        Super.DoEffect();
        // Weapon Sway code below was taken from Diamond Dragon
        //  and was first made by Nash Muhandes, adapted & edited for my use.
        if( owner && owner is "PlayerPawn" )
        {
            //  TODO
            //      Make this sway configurable and also
            //      add horizontal sway obviously.
            if( !playerOwner ) {
                playerOwner = PlayerPawn(owner);
            }

            let psp = playerOwner.player.psprites;
            let wep = playerOwner.player.ReadyWeapon;
            if( !psp || !wep ) return;

            // vertical offset
            double ypitch = -playerOwner.pitch;
            ypitch = SWAY_SENSITIVITY_Y * ypitch / 90.0;

            bool bCanSway = (
                        (playerOwner.player.WeaponState & WF_WEAPONREADY)
                        || (playerOwner.player.WeaponState & WF_WEAPONREADYALT)
                        || (playerOwner.player.WeaponState & WF_WEAPONRELOADOK)
                        || (playerOwner.player.WeaponState & WF_WEAPONZOOMOK)
                        || (playerOwner.player.WeaponState & WF_WEAPONSWITCHOK)
                    );

            // main offset logic
            if( psp && bCanSway )
            {
                psp.y = ypitch + 32;

                // add jump velocity to Y
                // psp.y += (plr.Vel.Z * 2);
                psp.y = clamp(psp.y, SWAY_MIN_Y, SWAY_MAX_Y);
            }
        }
    }


    /*
        Custom functions & action functions
    */

    // Simplified shooting logic + mod extras
    action void A_MFireWeapon(
            double horzSpread, double vertSpread, int numBullets, int damagePerBullet, 
            int flags = FBF_USEAMMO|FBF_NOFLASH|FBF_NORANDOM
            )
    {
        // Physical recoil applied to player's view
        if( invoker.verticalRecoil != 0 ) {
            A_SetPitch(self.pitch - abs(invoker.verticalRecoil), SPF_INTERPOLATE|SPF_FORCECLAMP);
        }
        if( invoker.horizontalRecoil != 0 ) {
            A_SetAngle(self.angle + invoker.horizontalRecoil, SPF_INTERPOLATE);
        }

        //  TODO:
        //      Add different bullet puffs for weapons                     VVVV
        A_FireBullets(horzSpread, vertSpread, numBullets, damagePerBullet, "BulletPuff", flags);
    }
    

	// The smoke spawning logic is almost entirely from Project Brutality
    //  All I did was adapt for my (current) needs and make it particle-based instead of spawning an Actor
    //  Without PB I have no idea how I'd do this
	static Vector3 RelativeToGlobalCoords(Vector3 startpos, Vector3 viewAngles, Vector3 offset)
	{
		Quat dir = Quat.FromAngles(viewAngles.x, viewAngles.y, viewAngles.z);
		Vector3 ofs = dir * (offset.x, -offset.y, offset.z);

		return level.vec3offset(startpos, ofs);
	}

    /*
        TODO: Nearly every value here is hardcoded.
                I believe there are possibilities to make this more flexible, though for now it'll stay like this 
    */
	action void A_SpawnGunSmoke(int howMany = 1)
	{
		double fovOfs = (120 - self.player.desiredfov) / 3.f; // good enough
		
        // These *relative* offset vectors, from what i've tested, function like this:
        //              (-backward/+forward, -left/+right,  -down/+up)
        //      Assuming we're viewing from the player's POV.  
        Vector3 posofs;
        Vector3 velofs;
		Vector3 spos;
		Vector3 svel;
        double rndroll;
        String smokename;
        for( int i = 0; i < howMany; i++ )
        {
            FSpawnParticleParams params;
            /* Variable setup */
            posofs = (frandom[smk](-1, 3), frandom[smk](-4, 4), frandom[smk](-0.5, 1.0));
            posofs.z -= 10.5;
		    posofs.y += 15;
            velofs = (frandom[smk](0.2, 2.2), random2[smk](3), frandom[smk](0.1, 1.0));
            
            /* Calculate relative to absolute coords */
            spos = MercilessWeapon.RelativeToGlobalCoords( (self.pos.xy, self.player.viewz), (self.angle, self.pitch, self.roll), (self.radius + posofs.y - (5.0 * abs(sin(self.pitch))) + fovOfs, -posofs.x, posofs.z));
            svel = MercilessWeapon.RelativeToGlobalCoords( (self.vel.xy, 0), (self.angle, self.pitch, self.roll), velofs );

            /* Smoke parameters */
            smokename = invoker.smokeSprites[ random[smk](0, invoker.smokeSprites.Size()-1) ]; 
            params.pos = spos;
            params.style = STYLE_Translucent;
            params.lifetime = 10 + random[smk](0,15); // between 10 to 25 tics

            rndroll = (1.0 + frandom[smk](0.0, 7.0)) * randompick[smk](-1,1); // between (-)1 to (-)8
            params.flags = SPF_ROLL|SPF_ROLLCENTER;
            params.rollvel = rndroll;
            
            params.color1 = "";
            params.texture = TexMan.CheckForTexture(smokename);
            int w, h;
            [w, h] = TexMan.GetSize(params.texture);
            params.size = h*(frandom[smk](0.3,0.5)); // height should always be the greatest
            
            params.startalpha = 0.5;
            params.startroll = 0.0;
            params.fadestep = -1;

            params.vel = svel;

            level.SpawnParticle(params);
        }

	}


    // Standard muzzleflash creation for weapons
    action void A_MCreateFlash(int renderstyle = STYLE_Add)
    {
        A_Overlay(invoker.FLASH_LAYER,            "MuzzleFlash");
        A_OverlayFlags(invoker.FLASH_LAYER,       PSPF_RENDERSTYLE|PSPF_ALPHA, set:true);
        A_OverlayRenderstyle(invoker.FLASH_LAYER, renderstyle);
        A_OverlayAlpha(invoker.FLASH_LAYER,       0.5);
    }


    // better wrapper for a_quakeex
    // TODO: Of course, this may need adjustments over time, and take weapon recoil values into account
    action void A_MShakeCamera(Vector3 xyz, double duration)
    {
        A_QuakeEx(xyz.x, xyz.y, xyz.z, duration, 0, tremrad:50, sfx:"", flags:WOF_RELATIVE, rollintensity:0.5, rollwave:1.0);
    }

}