version "4.14.3"

// weapon effects
#include "./zscript/merciless/Effects/BulletCasings.zsc"

// weapons
#include "./zscript/merciless/Weapons/WeaponBase.zsc"
#include "./zscript/merciless/Weapons/M9Pistol.zsc"
#include "./zscript/merciless/Weapons/SuperShotgun.zsc"

// other functionality
#include "./zscript/merciless/WeaponEventHandler.zsc"

// player
#include "./zscript/merciless/PlayerClass.zsc"