class MyPlayer : DoomPlayer
{
    Default
    {
        // Player.StartItem "Shell", 50;
        Player.StartItem "BerettaM9";
		Player.StartItem "Pistol";
		Player.StartItem "Clip", 150;
		//Player.StartItem "MP9Smg";
        Player.WeaponSlot 2, "BerettaM9";


		// Player.StartItem "MDShotgun";
		// Player.StartItem "MercilessSSG";
		// Player.StartItem "Shell", 50;
        // Player.WeaponSlot 3, "MercilessSSG", "PumpShotgun", "MDShotgun";
    }
}