
/*
    Mixin for broader weapon-specific functions/helpers.
*/
mixin class WeaponFunctions
{
    action bool IsHoldingAltFire()      { return self.player.buttons & BT_ALTATTACK; }
    action bool IsHoldingPrimaryFire()  { return self.player.buttons & BT_ATTACK; }

    // Returns true if the player just released button 'which'.
    action bool JustReleased(int which) {
        return !(player.buttons & which) && player.oldbuttons & which;
    }

    // For checking the player's preferred aiming method
    action bool IsToggleAimMode() { 
        return CVar.GetCvar("toggle_aim_mode", player).GetBool(); // cache this later 
    }
}

class MDUtils : Object
{

    /***    Conversion from relative coords to global ones.
     **     Credits to PB for this specific code, although I also found it on the ZDoom wiki.
     **        +X: Forward. -X: Backward.
     **        +Y: Left.    -Y: Right.
     **        +Z: Up.      -Z: Down.
     **     Y sign is inverted, so it becomes easier to understand... */
	static
    Vector3 RelativeToGlobalCoords(Vector3 startpos, Vector3 viewAngles, Vector3 offset)
	{
		Quat dir = Quat.FromAngles(viewAngles.x, viewAngles.y, viewAngles.z);
		Vector3 ofs = dir * (offset.x, -offset.y, offset.z);

		return level.vec3offset(startpos, ofs);
	}
    
}