
/*
    This class is used to create bullet tracers, and manage
     any other required extra weapon functionality.
*/
class WeaponEventHandler : EventHandler
{
	static const color _colors[] = {
		"9b 5b 13",
		"af 7b 1f",
		"c3 9b 2f",
		"c3 9b 2f" /* appears twice so a segment of this color is longer
					than the others. */
	};

	const TRACERSCALE		= 6.0;
	const TRACERSTEP		= 0.01;
    const TRACERLENGTH      = 80;
    const TRACERSPEED       = 170;

    const DISTANCE_THRESHOLD = 2000; // beyond this, the tracers get a fixed-tic lifetime


    override bool WorldHitscanPreFired(WorldEvent e)
    {
        if( e.thing && e.thing.player )
        {
            let plr = PlayerPawn(e.thing);
         
            let correctZOffset = plr.height * 0.5 - plr.floorclip + plr.AttackZOffset * plr.player.crouchFactor;
            let startPos = plr.pos.PlusZ(correctZOffset);
                
            FLineTraceData tr;
            plr.LineTrace(
                e.AttackAngle, PLAYERMISSILERANGE, e.AttackPitch, flags:0, offsetz:correctZOffset, data:tr);
            
            Vector3 endTarget, diff, dir;
            endTarget = tr.HitLocation;
            diff = level.Vec3Diff(startPos, endTarget);
            dir = diff.Unit();
            
            let shotDistance = diff.Length();
            int tics;
            if( shotDistance > DISTANCE_THRESHOLD ) {
                tics = TICRATE*3; // a fixed 3 seconds
            } 
            else {
                tics = floor(shotDistance / TRACERSPEED);
            }

            SpawnTracerParticles(startPos, dir, tics);
        }

        return false;
    }


    private void SpawnTracerParticles(Vector3 startPos, Vector3 dir, int particleLifetime)
    {
        Vector3 velocity = dir * TRACERSPEED;
        Vector3 particleEnd = startPos + (dir * TRACERLENGTH);

        FSpawnParticleParams fp;
        for( float i = 0.0; i < 1; i += TRACERSTEP )
        {
            fp.color1 = _colors[clamp(i * _colors.Size(), 0, _colors.Size() -1 )];

            fp.pos.x = lerp(startPos.x, particleEnd.x, i);
            fp.pos.y = lerp(startPos.y, particleEnd.y, i);
            fp.pos.z = lerp(startPos.z, particleEnd.z, i);

            fp.vel = velocity;
            fp.startalpha = 1.0;
            fp.style = STYLE_Add;
            fp.flags = SPF_FULLBRIGHT;

            fp.lifetime = particleLifetime;
            fp.size = TRACERSCALE * i;

            level.SpawnParticle(fp);
        }
    }

	float lerp(float v0, float v1, float t) {
		return (1 - t) * v0 + t * v1;
	}
}